steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/twitter-support-chatbot', '.']
    env:
      - 'HUGGINGFACE_ENDPOINT_URL=${_HUGGINGFACE_ENDPOINT_URL}'
      - 'HUGGINGFACE_TOKEN=${_HUGGINGFACE_TOKEN}'
      - 'GCS_BUCKET_NAME=${_GCS_BUCKET_NAME}'
      - 'GCS_CREDENTIALS=${_GCS_CREDENTIALS}'
      - 'REDIS_HOST=${_REDIS_HOST}'
      - 'REDIS_PORT=${_REDIS_PORT}'
      - 'REDIS_PASSWORD=${_REDIS_PASSWORD}'
      - 'CACHE_TTL=${_CACHE_TTL}'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/twitter-support-chatbot']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'twitter-support-chatbot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/twitter-support-chatbot'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'HUGGINGFACE_ENDPOINT_URL=${_HUGGINGFACE_ENDPOINT_URL},HUGGINGFACE_TOKEN=${_HUGGINGFACE_TOKEN},GCS_BUCKET_NAME=${_GCS_BUCKET_NAME},GCS_CREDENTIALS=${_GCS_CREDENTIALS},REDIS_HOST=${_REDIS_HOST},REDIS_PORT=${_REDIS_PORT},REDIS_PASSWORD=${_REDIS_PASSWORD},CACHE_TTL=${_CACHE_TTL}'
      - '--port'
      - '8000'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'

images:
  - 'gcr.io/$PROJECT_ID/twitter-support-chatbot'

substitutions:
  _HUGGINGFACE_ENDPOINT_URL: 
  _HUGGINGFACE_TOKEN:
  _GCS_BUCKET_NAME: twitter_chat_history
  _GCS_CREDENTIALS: $(cat credentials.json | jq -c .)
  _REDIS_HOST: redis-host  # Replace with your Redis host
  _REDIS_PORT: "6379"
  _REDIS_PASSWORD: ""  # Set a password if needed
  _CACHE_TTL: "3600"  # 1 hour cache TTL 
